### ISSUE TITLE
Feedback on landing page

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [nmfs-fish-tools/ASAP#1]
1. PDF link just downloads the webpage
2. Need tooltip or more info on badge
More information that could be helpful: https://repository.library.noaa.gov/view/noaa/5027
https://www.researchgate.net/profile/Victor_Restrepo/publication/266334996_A_Flexible_Forward_Age-Structured_Assessment_Program/links/57348b3208aea45ee83ac80b/A-Flexible-Forward-Age-Structured-Assessment-Program.pdf

**Comment by CorinneBassin-NOAA** [comment]
@ChristineStawitz-NOAA  I made the changes requested.  For now I have a tooltip place holder for the badges.  I will work on a better UX for the badges and we should come up with 3? levels of badges to use.

I also made a few changes towards 508 compliance.
